---
title: "ISEC_abstract"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Analyzing geostatistical data (coordinate referenced observations) is becoming increasingly common in ecology; these data often include a discrete temporal dimension, such as monthly or yearly samples. Computational tools to model spatial and spatiotemporal processes have advanced rapidly over the last decade; examples of R packages for analyzing geostatistical data include `mgcv`, `INLA` and `inlabru`, `VAST`, and `spBayes`. These packages are 
In this talk, we present a new R package `sdmTMB`. The goals of `sdmTMB` are not to replace functionality in existing packages, but provide a user friendly implementation of SPDE models -- similar to the popular package `glmmTMB`, but with the addition of spatial models. We extend the generalized linear mixed models (GLMMs) familiar to ecologists to include the following optional features:
* spatial fields
* spatiotemporal fields, that may be independent by year or modeled with random walks or autoregressive processes
* smooth terms for covariates, using the familiar `s()` notation in `mgcv`
* spatially varying coefficient models (SVC)
* non-stationary covariates (coefficients modeled as random walks)

Like `glmmTMB`, estimation is performed in `sdmTMB` via maximum likelihood, implemented  using the Template Model Builder (TMB) software. The `sdmTMB` package also allows for models to be passed to Stan, allowing for efficient Bayesian estimation. 

We provide a general overview of the package structure, and demonstrate features using several examples (Snowy Owl winter irruptions in North America, and a dataset describing the distribution of Pacific cod in British Columbia). We highlight the advantages of using `sdmTMB` for these classes of models: (1) estimation in TMB is often faster than with alternative estimation routines, (2) `sdmTMB` provides a user friendly interface that is familiar to many R users, (3) `sdmTMB` allows for easy out of sample model validation, not found in other packages, (4) non-stationary processes are easily constructed with the formula interface (time varying coefficients, spatially varying coefficient models). For analysts fitting species distribution models (SDMs) or estimating population abundance trends, `sdmTMB` provides specific functions for performing these calculations. 


